# =============================================================================
# AUSTRALIAN NATIONAL UNIVERSITY OPEN SOURCE LICENSE (ANUOS LICENSE)
# VERSION 1.3
# 
# The contents of this file are subject to the ANUOS License Version 1.2
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at:
# 
#   http://datamining.anu.edu.au/linkage.html
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Software is: "C05.py"
# 
# The Initial Developers of the Original Software are:
#   Peter Christen
# 
# Copyright (C) 2002 - 2011 the Australian National University and
# others. All Rights Reserved.
# 
# Contributors:
# 
# Alternatively, the contents of this file may be used under the terms
# of the GNU General Public License Version 2 or later (the "GPL"), in
# which case the provisions of the GPL are applicable instead of those
# above. The GPL is available at the following URL: http://www.gnu.org/
# If you wish to allow use of your version of this file only under the
# terms of the GPL, and not to allow others to use your version of this
# file under the terms of the ANUOS License, indicate your decision by
# deleting the provisions above and replace them with the notice and
# other provisions required by the GPL. If you do not delete the
# provisions above, a recipient may use your version of this file under
# the terms of any one of the ANUOS License or the GPL.
# =============================================================================

# =============================================================================
# Start of Febrl project module: "C05.py"
#
# Generated using "guiFebrl.py" on Sat Sep 13 15:42:47 2014
# =============================================================================

# Import necessary modules (Python standard modules first, then Febrl modules)

import logging

import classification
import comparison
import dataset
import encode
import indexing
import measurements
import mymath
import output
import stringcmp

# -----------------------------------------------------------------------------
# Intialise a logger, set level to info oe warning
#
log_level = logging.INFO # logging.WARNING

my_logger = logging.getLogger()
my_logger.setLevel(log_level)

# -----------------------------------------------------------------------------
# Febrl project type: Link
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------

# Define input data set A:
#
data_set_a = dataset.DataSetCSV(description="Data set generated by Febrl GUI (note TAB data set is implemented as CSV data set with \t delimiter)",
                                access_mode="read",
                                strip_fields=False,
                                miss_val=[''],
                                rec_ident="field-0",
                                file_name="C:\Users\Abdullah\Dropbox\rla\TestData\DataIn5k1.txt",
                                header_line=False,
                                delimiter="\t",
                                field_list = [("field-0",0),
                                              ("field-1",1),
                                              ("field-2",2),
                                              ("field-3",3),
                                              ("field-4",4),
                                              ("field-5",5)])

# Define input data set B:
#
data_set_b = dataset.DataSetCSV(description="Data set generated by Febrl GUI (note TAB data set is implemented as CSV data set with \t delimiter)",
                                access_mode="read",
                                strip_fields=False,
                                miss_val=[''],
                                rec_ident="field-0",
                                file_name="C:\Users\Abdullah\Dropbox\rla\TestData\DataIn5k2.txt",
                                header_line=False,
                                delimiter="\t",
                                field_list = [("field-0",0),
                                              ("field-1",1),
                                              ("field-2",2),
                                              ("field-3",3),
                                              ("field-4",4),
                                              ("field-5",5)])


# -----------------------------------------------------------------------------

# Define field comparison functions
#
fc_funct_1 = comparison.FieldComparatorEditDist(agree_weight = 1.0,
                                                description = "Edit-Dist-field-1-field-1",
                                                disagree_weight = 0.0,
                                                missing_weight = 0.0,
                                                threshold = 0.5)

field_comp_list = [(fc_funct_1, "field-1", "field-1")]

rec_comp = comparison.RecordComparator(data_set_a, data_set_b, field_comp_list)

# -----------------------------------------------------------------------------

# Define indices for "blocking"
#
index_def_1 = [["field-1", "field-1", False, False, 7, [encode.get_substring, 0,6]]]

index = indexing.CanopyIndex(dataset1 = data_set_a,
                             dataset2 = data_set_b,
                             rec_comparator = rec_comp,
                             progress_report = 10,
                             index_sep_str = "",
                             skip_missing = True,
                             index_def = [index_def_1],
                             canopy_method = ("jaccard","threshold",.8,.3),
                             q = 3,
                             delete_perc = 100,
                             padded = True)

# Build and compact index
#
index.build()

index.compact()

# Do record pair comparisons
#
[field_names_list, w_vec_dict] = index.run()

# -----------------------------------------------------------------------------

# Define weight vector (record pair) classifier
#
classifier = classification.FellegiSunter(lower_threshold = 0.3,
                                          upper_threshold = 0.8)

# Unsupervised training of classifier
#
class_w_vec_dict = w_vec_dict  # Use orignal weight vector dictionary

classifier.train(class_w_vec_dict, set(), set())

# Classify all weight vectors
#
[m_set, nm_set, pm_set] = classifier.classify(class_w_vec_dict)

# -----------------------------------------------------------------------------

# Define output file options
#
histo_str_list = output.GenerateHistogram(class_w_vec_dict, 1.0)

for line in histo_str_list:
  print line
output.SaveMatchStatusFile(class_w_vec_dict, m_set, "C:\Users\Abdullah\Dropbox\rla\TestData\DataOut5k.txt")


# =============================================================================
# End of Febrl project module: "C05.py"
# =============================================================================
